# use rspec-rerun for flickering tests due to poltergeist time outs
language: ruby
rvm:
  - 2.4.1
services:
  - mongodb
notifications:
  email:
    - web@mars-hq.com
  irc:
    channels:
      - 'irc.freednode.net#ogchatter'
    on_success: change
    use_notice: true
    skip_join: true